
server:
    port: 8088
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: spring_boot_mongo_app
    application:
        name: superhero-service
